cat("# Autogenerated from data-raw/namespace.R\n\n", file = "NAMESPACE")

append <- . %>% cat(sep="\n", file = "NAMESPACE", append = TRUE)

c("dplyr_compat", "plyr_compat", "plyr_warn_compat") %>%
  sprintf("export(%s)", .) %>%
  append

"" %>% append

getNamespaceExports("plyr") %>%
  setdiff(c("mutate", "summarise", "summarize", "arrange", "failwith", "id", "rename", "desc", "count")) %>%
  sprintf('"%s"', .) %>%
  sprintf("importFrom(plyr,%s)", .) %>%
  append
